# Generated by Django 2.0.10 on 2019-06-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_managing'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcmToken',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
