# Generated by Django 2.0.10 on 2019-06-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_fcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwtToken',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
