# Generated by Django 2.0.10 on 2019-08-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0026_auto_20190813_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='pump_1_freq',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_1_operating_rate',
            field=models.FloatField(),
        ),
    ]
