# Generated by Django 2.0.10 on 2019-08-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0030_auto_20190816_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='pump_1_operating_rate',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_2_operating_rate',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_3_operating_rate',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_4_operating_rate',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_2_freq',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_3_freq',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_4_freq',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
