# Generated by Django 2.0.10 on 2019-08-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0032_auto_20190816_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='pump_4_freq',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_2_freq',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_3_freq',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
