# Generated by Django 2.0.10 on 2019-07-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0012_auto_20190601_0036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pump',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='town',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_1_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_1_current',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_1_freq',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_1_operating_rate',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_1_power',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_2_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_2_current',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_2_freq',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_2_operating_rate',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_2_power',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_3_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_3_current',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_3_freq',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_3_operating_rate',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_3_power',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_4_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_4_current',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_4_freq',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_4_operating_rate',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_4_power',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
