# Generated by Django 2.0.10 on 2019-07-08 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0013_auto_20190708_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='pump_1_auto',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_1_current',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_1_freq',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_1_operating_rate',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_1_power',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_2_auto',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_2_current',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_2_freq',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_2_operating_rate',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_2_power',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_3_auto',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_3_current',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_3_freq',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_3_operating_rate',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_3_power',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_4_auto',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_4_current',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_4_freq',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_4_operating_rate',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_4_power',
        ),
    ]
