# Generated by Django 2.0.10 on 2019-07-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0018_auto_20190708_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='pump_2_current',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_2_freq',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_2_operating_rate',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_2_power',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_3_current',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_3_freq',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_3_operating_rate',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_3_power',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_4_current',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_4_freq',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_4_operating_rate',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_4_power',
            field=models.FloatField(blank=True),
        ),
    ]
