# Generated by Django 2.0.10 on 2019-07-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0021_auto_20190708_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pump',
            name='sector',
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='pressure',
            new_name='discharge_pressure',
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='water_level',
            new_name='pump_1_low_water',
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='dis_pressure',
            new_name='sector_id',
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_2_low_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_3_low_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_4_low_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='suction_pressure',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pump',
        ),
    ]
