# Generated by Django 2.0.10 on 2019-07-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0022_auto_20190710_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='pump_1_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_2_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_3_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_4_on',
            field=models.BooleanField(default=False),
        ),
    ]
