# Generated by Django 2.0.10 on 2019-07-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0023_auto_20190710_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='city',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='sector_set', to='pumps.City'),
        ),
    ]
