# Generated by Django 2.0.10 on 2019-08-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0024_sector_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sector',
            old_name='pump_1_disorder',
            new_name='pump_1_disorder_a',
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='pump_2_disorder',
            new_name='pump_1_disorder_b',
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='pump_3_disorder',
            new_name='pump_2_disorder_a',
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='pump_4_disorder',
            new_name='pump_2_disorder_b',
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_3_disorder_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_3_disorder_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_4_disorder_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_4_disorder_b',
            field=models.BooleanField(default=False),
        ),
    ]
