# Generated by Django 2.0.10 on 2019-08-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0025_auto_20190813_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='pump_1_disorder_a',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_1_disorder_b',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_2_disorder_a',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_2_disorder_b',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_3_disorder_a',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_3_disorder_b',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_4_disorder_a',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_4_disorder_b',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
