# Generated by Django 2.0.10 on 2019-08-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0027_auto_20190816_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='pump_1_operating_rate',
        ),
    ]
