# Generated by Django 2.0.10 on 2019-08-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0028_remove_sector_pump_1_operating_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='pump_2_operating_rate',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_3_operating_rate',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_4_operating_rate',
        ),
    ]
