# Generated by Django 2.0.10 on 2019-08-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0029_auto_20190816_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='pump_2_freq',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_3_freq',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_4_freq',
            field=models.FloatField(),
        ),
    ]
