# Generated by Django 2.0.10 on 2019-08-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0031_auto_20190816_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='pump_1_operating_rate',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_2_operating_rate',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_3_operating_rate',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_4_freq',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pump_4_operating_rate',
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_2_freq',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_3_freq',
            field=models.FloatField(),
        ),
    ]
