# Generated by Django 2.0.10 on 2019-08-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0033_auto_20190816_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='pump_1_freq',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_3_freq',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pump_4_freq',
            field=models.FloatField(default=0),
        ),
    ]
